### ISSUE TITLE
No link to google doc in README.md

### ISSUE THREAD

**Issue by AAorris** [fatty-tuna/vr-vs-world#2]
It would be nice to get everyone comfortable with working together on files - once Kio's here, could you add a link to the google doc to our README.md file?

**Comment by AAorris** [comment]
Kio, can you post that for me?

**Comment by tayloraudesigns** [comment]
@Kalokoi It has been four days since the fabled Google Doc has been alluded. During the hunt, we have lost the almighty leader Jeffrey to Hearthstone and TERA. He shall be missed. ._.7

**Comment by tayloraudesigns** [comment]
https://docs.google.com/document/d/17T2n7Lj_8588gPt8yydxoTG4o62AaeDXxeYlPDn74Qs/edit
